//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiLabelFormats.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DigiLabelFormats.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 60x49.
        /// </summary>
        internal static string FrmGenerateLabelFormat_GenerateFormat__60x49 {
            get {
                return ResourceManager.GetString("FrmGenerateLabelFormat_GenerateFormat__60x49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  niet gevonden..
        /// </summary>
        internal static string FrmLabelFormats_btnOpenInLabelDesigner_Click__niet_gevonden_ {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnOpenInLabelDesigner_Click__niet_gevonden_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg eerst een of meerdere formaten toe.
        /// </summary>
        internal static string FrmLabelFormats_btnOverzicht_Click_Voeg_eerst_een_of_meerdere_formaten_toe {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnOverzicht_Click_Voeg_eerst_een_of_meerdere_formaten_toe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bewaar het formaatbestand dat je hebt samengesteld.
        /// </summary>
        internal static string FrmLabelFormats_btnSaveFormatFile_Click_Bewaar_het_formaatbestand_dat_je_hebt_samengesteld {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnSaveFormatFile_Click_Bewaar_het_formaatbestand_dat_je_hebt_sam" +
                        "engesteld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dat bestanden | *.dat.
        /// </summary>
        internal static string FrmLabelFormats_btnSaveFormatFile_Click_dat_bestanden_____dat {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnSaveFormatFile_Click_dat_bestanden_____dat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een formaat.
        /// </summary>
        internal static string FrmLabelFormats_btnSendWithDigiDriver_Click_Selecteer_een_formaat {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnSendWithDigiDriver_Click_Selecteer_een_formaat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen database gevonden.
        /// </summary>
        internal static string FrmLabelFormats_btnToevoegen_Click_Geen_database_gevonden {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnToevoegen_Click_Geen_database_gevonden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slechts 9 formaten mogelijk.
        /// </summary>
        internal static string FrmLabelFormats_btnToevoegen_Click_Slechts_9_formaten_mogelijk {
            get {
                return ResourceManager.GetString("FrmLabelFormats_btnToevoegen_Click_Slechts_9_formaten_mogelijk", resourceCulture);
            }
        }
    }
}
